# coding: utf-8

"""
    BloxOne Cloud EP API

    BloxOne Endpoint is a lightweight mobile agent that redirects DNS traffic from your remote devices to the BloxOne Cloud. It allows you to apply applicable security policies to your roaming end users in remote sites and branch offices.  In order for end users to connect to Infoblox cloud services, you must download and install BloxOne Endpoint on their devices. The client enforces security policies that you apply to the remote networks, regardless of where your end users are and which networks they are connected to. BloxOne Endpoint listens on port 53 of the device. If other software listens on the same port, DNS traffic cannot be redirected to BloxOne Cloud, and your device will not be protected by BloxOne Endpoint.  When you use the BloxOne Endpoint, DNS queries are sent to BloxOne Cloud directly except for (1) queries that target the bypassed domains and (2) internal domains collected through the DHCP server. If you have internal domains that are served by your local DNS servers and you want to reach them without interruptions, you should consider adding them to the bypassed internal domains list so that DNS queries for these internal domains are sent to the local DNS servers instead of BloxOne Cloud.  BloxOne Endpoint supports dual-stack IPv4 and IPv6 DNS configurations, thereby protecting all devices regardless of their network environments. BloxOne Endpoint in a dual-stack environment is able to proxy IPv6 DNS queries and forward them to BloxOne Cloud over IPv4.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.atcep_roaming_device_read_response import AtcepRoamingDeviceReadResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestAtcepRoamingDeviceReadResponse(unittest.TestCase):
    """AtcepRoamingDeviceReadResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAtcepRoamingDeviceReadResponse(self):
        """Test AtcepRoamingDeviceReadResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.atcep_roaming_device_read_response.AtcepRoamingDeviceReadResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
