# coding: utf-8

# flake8: noqa

"""
    BloxOne Cloud EP API

    BloxOne Endpoint is a lightweight mobile agent that redirects DNS traffic from your remote devices to the BloxOne Cloud. It allows you to apply applicable security policies to your roaming end users in remote sites and branch offices.  In order for end users to connect to Infoblox cloud services, you must download and install BloxOne Endpoint on their devices. The client enforces security policies that you apply to the remote networks, regardless of where your end users are and which networks they are connected to. BloxOne Endpoint listens on port 53 of the device. If other software listens on the same port, DNS traffic cannot be redirected to BloxOne Cloud, and your device will not be protected by BloxOne Endpoint.  When you use the BloxOne Endpoint, DNS queries are sent to BloxOne Cloud directly except for (1) queries that target the bypassed domains and (2) internal domains collected through the DHCP server. If you have internal domains that are served by your local DNS servers and you want to reach them without interruptions, you should consider adding them to the bypassed internal domains list so that DNS queries for these internal domains are sent to the local DNS servers instead of BloxOne Cloud.  BloxOne Endpoint supports dual-stack IPv4 and IPv6 DNS configurations, thereby protecting all devices regardless of their network environments. BloxOne Endpoint in a dual-stack environment is able to proxy IPv6 DNS queries and forward them to BloxOne Cloud over IPv4.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.bundle_api import BundleApi
from swagger_client.api.roaming_device_groups_api import RoamingDeviceGroupsApi
from swagger_client.api.roaming_devices_api import RoamingDevicesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.atcep_bundle import AtcepBundle
from swagger_client.models.atcep_bundle_response import AtcepBundleResponse
from swagger_client.models.atcep_net_info import AtcepNetInfo
from swagger_client.models.atcep_roaming_device import AtcepRoamingDevice
from swagger_client.models.atcep_roaming_device_group import AtcepRoamingDeviceGroup
from swagger_client.models.atcep_roaming_device_group_create_response import AtcepRoamingDeviceGroupCreateResponse
from swagger_client.models.atcep_roaming_device_group_delete_request import AtcepRoamingDeviceGroupDeleteRequest
from swagger_client.models.atcep_roaming_device_group_read_response import AtcepRoamingDeviceGroupReadResponse
from swagger_client.models.atcep_roaming_device_group_update import AtcepRoamingDeviceGroupUpdate
from swagger_client.models.atcep_roaming_device_group_update_response import AtcepRoamingDeviceGroupUpdateResponse
from swagger_client.models.atcep_roaming_device_groups_multi_response import AtcepRoamingDeviceGroupsMultiResponse
from swagger_client.models.atcep_roaming_device_multi_response import AtcepRoamingDeviceMultiResponse
from swagger_client.models.atcep_roaming_device_read_response import AtcepRoamingDeviceReadResponse
from swagger_client.models.atcep_roaming_device_update_request import AtcepRoamingDeviceUpdateRequest
from swagger_client.models.atcep_roaming_device_update_response import AtcepRoamingDeviceUpdateResponse
from swagger_client.models.atcep_roaming_devices_csv_list_response import AtcepRoamingDevicesCSVListResponse
from swagger_client.models.net_info_state import NetInfoState
